; This file was auto-generated by drush make
core = 7.17

api = 2
projects[drupal][version] = "7.17"

; Modules
projects[admin_menu][version] = "3.0-rc3"

projects[block_class][version] = "1.2"

projects[ctools][version] = "1.2"

projects[chart][version] = "1.1"

projects[context][version] = "3.0-beta4"

projects[date][version] = "2.6"

projects[defaultcontent][version] = "1.0-alpha6"

projects[devel][version] = "1.3"

projects[entity][version] = "1.0-rc3"

projects[features_extra][version] = "1.0-alpha1"

projects[features][version] = "1.0"

projects[fieldable_panels_panes][version] = "1.2"

projects[media][version] = "1.2"

projects[google_analytics_reports][version] = "1.3"

projects[google_analytics][version] = "1.3"

projects[imce][version] = "1.6"

projects[jcarousel][version] = "2.6"

projects[libraries][version] = "2.0"

projects[link][version] = "1.0"

projects[media_vimeo][version] = "1.0-beta5"

projects[media_youtube][version] = "2.0-rc1"

projects[menu_block][version] = "2.3"

projects[metatag][version] = "1.0-beta4"

projects[module_filter][version] = "1.7"

projects[oauth][version] = "3.0"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[profile2][version] = "1.2"

projects[strongarm][version] = "2.0"

projects[superfish][version] = "1.8"

projects[themekey][version] = "2.3"

projects[token][version] = "1.4"

projects[views][version] = "3.5"

projects[views_bulk_operations][version] = "3.0"

projects[views_horizontal_slider][version] = "1.0"

projects[views_slideshow][version] = "3.0"

projects[webform][version] = "3.18"

projects[menu_import][version] = "1.2"

; Themes
projects[omega][version] = "3.1"

; Libraries
libraries[superfish][download][type] = "git"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal.git"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor%20for%20Drupal/CKEditor%203.6.3%20for%20Drupal/ckeditor_3.6.3_for_drupal_7.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

projects[features_campus][type] = "module"
projects[features_campus][download][type] = "git"
projects[features_campus][download][url] = "https://github.com/tuongduy/influencer_feature_export.git"

projects[vietcoop][type] = "module"
projects[vietcoop][download][type] = "git"
projects[vietcoop][download][url] = "https://github.com/tuongduy/influencer_module.git"

; Themes
projects[themes][type] = "theme"
projects[themes][download][type] = "git"
projects[themes][download][url] = "https://github.com/tuongduy/influencer_themes.git"

;Profile
projects[campus][type] = profile
projects[campus][download][type] = git
projects[campus][download][url] = "https://github.com/tuongduy/influencer_campus.git"